title: Guangxing Han
description: Phd student at Tsinghua University, major in computer vision and deep learning.
show_downloads: false
git_branch: master
logo_url:
google_analytics: true
theme: 
wiki_folder: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
